### ISSUE TITLE
リンク先の言語

### ISSUE THREAD

**Issue by naohanpen** [jawordpressorg/theme-handbook#4]
ドキュメント内でしばしば、別のセッションへのリンクがあります。
リンク先は英語ドキュメントのもののままで大丈夫ですか？

**Comment by miminari** [comment]
@naohanpen すみません、今頃Issueに気が付きました。
リンク先は日本語ドキュメントが存在しない場合は英語のママで良いと考えています。

**Comment by naohanpen** [comment]
@miminari 全然大丈夫です！承知いたしました✨
学校が忙しくて全然参加できてなくて、、こちらこそすみません🙏

**Comment by miminari** [comment]
@naohanpen いえいえ、学校最優先で！
ではこちらのIssueは一旦、解決済みとしてcloseしておきますね。
