### ISSUE TITLE
翻訳: /themes/getting-started/what-is-a-theme.md

### ISSUE THREAD

**Issue by naohanpen** [jawordpressorg/theme-handbook#6]
原文: https://developer.wordpress.org/themes/getting-started/what-is-a-theme.md

を

翻訳: https://github.com/jawordpressorg/theme-handbook/blob/main/theme/getting-started/what-is-a-theme.md

で翻訳します。

**Comment by t-hamano** [comment]
このページは翻訳完了していると思うので、クローズします。
